# Generated by Django 5.2.5 on 2025-09-03 06:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('transfer', 'Transfer'), ('update', 'Update'), ('exclusive', 'Exclusive'), ('match', 'Match'), ('rumor', 'Rumor'), ('analysis', 'Analysis')], default='update', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('news_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
